CREATE TABLE `invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`invoice_id` varchar(12) NOT NULL,
	`external_id` varchar(12) NOT NULL,
	`user_id` varchar(12) NOT NULL,
	`status` varchar(11) NOT NULL,
	`merchant_name` varchar(12) NOT NULL,
	`merchant_profile_picture_url` text NOT NULL,
	`amount` int NOT NULL,
	`expiry_date` timestamp NOT NULL,
	`invoice_url` text NOT NULL,
	`created` timestamp NOT NULL,
	`updated` timestamp NOT NULL,
	`currency` varchar(11) NOT NULL,
	`customer` json NOT NULL,
	`items` json NOT NULL,
	`fees` json,
	`available_banks` json,
	`available_retail_outlets` json,
	`available_ewallets` json,
	`available_qr_codes` json,
	`available_direct_debits` json,
	`available_paylaters` json,
	CONSTRAINT `invoices_id` PRIMARY KEY(`id`),
	CONSTRAINT `invoices_invoice_id_unique` UNIQUE(`invoice_id`)
);
