import {  mysqlTable, int, varchar, json, text, timestamp } from 'drizzle-orm/mysql-core';

export const invoices = mysqlTable('invoices', {
    id: int('id').primaryKey().autoincrement(),
    invoiceId: varchar({ length: 255 }).notNull().unique(),
    externalId: varchar({ length: 255 }).notNull(),
    userId: varchar({ length: 255 }).notNull(),
    status: varchar({ length: 255 }).notNull(),
    merchantName: varchar({ length: 255 }).notNull(),
    merchantProfilePictureUrl: text().notNull(),
    amount: int().notNull(),
    expiryDate: timestamp().notNull(),
    invoiceUrl: text().notNull(),
    created: timestamp().notNull().default(new Date()),
    updated: timestamp().notNull().default(new Date()),
    currency: varchar({ length: 255 }).notNull(),
    customer: json().notNull(),
    items: json().notNull(),
    fees: json(),
    availableBanks: json(),
    availableRetailOutlets: json(),
    availableEwallets: json(),
    availableQrCodes: json(),
    availableDirectDebits: json(),
    availablePaylaters: json(),
});
